spring.application.name=health-monitoring-backend
server.port=8080

app.upload-dir=uploads

# Emergency email notifications
app.notifications.email.enabled=true
app.notifications.email.to=pjvetheshsai@gmail.com
app.notifications.email.from=jvetheshsai65@gmail.com

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jvetheshsai65@gmail.com
spring.mail.password=hotxqwdrhtvmywxd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
